bugsnag:
    api_key: '%env(BUGSNAG_KEY)%'
    release_stage: '%env(BUGSNAG_STAGE)%'
    user: false
    notify_release_stages:
        - production
        #- development

services:
    Bugsnag\Client:
        alias: bugsnag