bugsnag:
    api_key: '%env(BUGSNAG_KEY)%'
    release_stage: '%env(BUGSNAG_STAGE)%'
    user: false
    notify_release_stages:
        - production
        #- development
    discard_classes:
        - Symfony\Component\HttpKernel\Exception\HttpException\RedirectException
        - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
        - Symfony\Component\Security\Core\Exception\AccessDeniedException

services:
    Bugsnag\Client:
        alias: bugsnag
