language: php

env:
    global:
        - SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
        - APP_ENV=test
        - APP_DEBUG=0

matrix:
    include:
        - php: 7.1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - bin/.phpunit

install: composer install --prefer-dist --no-interaction

script:
    - make test
    - make cs_dry_run

branches:
    only:
        - master
