monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: syslog
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        syslog:
            type: syslog
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
