faq:
  path:     /faq
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: content/faq.html.twig

sitemap:
  path:     /sitemap.xml
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: content/sitemap.xml.twig