homepage:
    path:     /
    defaults: { _controller: JoliCode\SecretSanta\Controller\ContentController::homepage }

hall_of_fame:
    path:     /hall-of-fame
    defaults: { _controller: JoliCode\SecretSanta\Controller\ContentController::hallOfFame }

stats:
    path:     /stats
    defaults: { _controller: JoliCode\SecretSanta\Controller\ContentController::stats }

terms:
    path:     /terms-of-service
    defaults: { _controller: JoliCode\SecretSanta\Controller\ContentController::terms }

privacy_policy:
    path:     /privacy-policy
    defaults: { _controller: JoliCode\SecretSanta\Controller\ContentController::privacyPolicy }

faq:
    path:     /faq
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: content/faq.html.twig

run:
    path:     /run/{application}
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController::run }

send_sample_message:
    path:     /sample-message/{application}
    methods:  POST
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController::sendSampleMessage }

send_messages:
    path:     /send-messages/{hash}
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController::sendMessages }

finish:
    path:     /finish/{hash}
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController::finish }

spoil:
    path:     /spoil
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController::spoil }

slack_authenticate:
    path:     /auth/slack
    defaults: { _controller: JoliCode\SecretSanta\Controller\SlackController::authenticate }

discord_authenticate:
    path:     /auth/discord
    defaults: { _controller: JoliCode\SecretSanta\Controller\DiscordController::authenticate }
